# Generated by Django 3.0.6 on 2023-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSelecionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('autorizado', models.BooleanField(default=False)),
                ('selecionado_por', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
