# Generated by Django 3.0.6 on 2023-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_numeroselecionado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroselecionado',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
