# Generated by Django 3.0.6 on 2023-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeroselecionado',
            name='selecionado_por',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
