# Generated by Django 3.0.6 on 2023-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230303_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroselecionado',
            name='autorizado',
        ),
    ]
