# Generated by Django 3.0.6 on 2023-03-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_numeroselecionado_autorizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroselecionado',
            name='selecionado_por',
        ),
    ]
