# Generated by Django 3.0.6 on 2023-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_numeroselecionado_selecionado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroselecionado',
            name='Pago',
            field=models.BooleanField(default=False),
        ),
    ]
