# Generated by Django 3.0.6 on 2023-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_numeroselecionado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroselecionado',
            name='Mensagem',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
