# Generated by Django 3.0.6 on 2023-03-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_numeroselecionado_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numeroselecionado',
            name='Mensagem',
        ),
    ]
