# Generated by Django 3.0.6 on 2023-03-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_numeroselecionado_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeroselecionado',
            old_name='Pago',
            new_name='pago',
        ),
    ]
