# Generated by Django 3.0.6 on 2023-03-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230304_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroselecionado',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
