# Generated by Django 3.0.6 on 2023-03-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_numeroselecionado_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeroselecionado',
            old_name='timestamp',
            new_name='selecionado_em',
        ),
    ]
